---
kind: pipeline
name: Build

trigger:
  branch:
  - main
  event:
  - push

steps:
  - name: Build image
    image: docker
    environment:
      HUB_USER:
        from_secret: hub_user
      HUB_PASSWORD: 
        from_secret: hub_password
    commands:
      - docker build --pull -t $DRONE_REPO:drone-dev .
      - docker login -u $HUB_USER -p $HUB_PASSWORD
      - docker push $DRONE_REPO:drone-dev
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: Scan image
    image: docker
    environment: 
      ANCHORE_CLI_USER:
        from_secret: anchore_cli_user
      ANCHORE_CLI_PASS:
        from_secret: anchore_cli_pass
      ANCHORE_CLI_URL:
        from_secret: anchore_cli_url
    commands:
      - docker run --rm -e ANCHORE_CLI_URL=$ANCHORE_CLI_URL -e ANCHORE_CLI_USER=$ANCHORE_CLI_USER -e ANCHORE_CLI_PASS=$ANCHORE_CLI_PASS anchore/engine-cli sh -c "anchore-cli image add --noautosubscribe $DRONE_REPO:drone-dev --annotation build_tool=drone --annotation build_number=$DRONE_BUILD_NUMBER && anchore-cli image wait $DRONE_REPO:drone-dev && anchore-cli evaluate check $DRONE_REPO:drone-dev"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: Promote image
    image: docker
    environment: 
      ANCHORE_CLI_USER:
        from_secret: anchore_cli_user
      ANCHORE_CLI_PASS:
        from_secret: anchore_cli_pass
      ANCHORE_CLI_URL:
        from_secret: anchore_cli_url
      HUB_USER:
        from_secret: hub_user
      HUB_PASSWORD: 
        from_secret: hub_password
    commands:
      - docker login -u $HUB_USER -p $HUB_PASSWORD
      - docker tag $DRONE_REPO:drone-dev $DRONE_REPO:drone-prod
      - docker push $DRONE_REPO:drone-prod
      - docker run --rm -e ANCHORE_CLI_URL=$ANCHORE_CLI_URL -e ANCHORE_CLI_USER=$ANCHORE_CLI_USER -e ANCHORE_CLI_PASS=$ANCHORE_CLI_PASS anchore/engine-cli sh -c "anchore-cli image add --noautosubscribe $DRONE_REPO:drone-prod --annotation build_tool=drone --annotation build_number=$DRONE_BUILD_NUMBER"
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  - name: Cleanup
    image: docker
    commands:
      - docker image rm $DRONE_REPO:drone-dev $DRONE_REPO:drone-prod
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
